'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3634
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("vDBCompare.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3 October 2008.
        '''</summary>
        Friend ReadOnly Property BuildDate() As String
            Get
                Return ResourceManager.GetString("BuildDate", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property check_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property configprev_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("configprev_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cooltext35829721() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cooltext35829721", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C:\Program Files\VistaDB 2.1.
        '''</summary>
        Friend ReadOnly Property DataBuilderDefaultDir() As String
            Get
                Return ResourceManager.GetString("DataBuilderDefaultDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C:\Program Files\VistaDB 3.
        '''</summary>
        Friend ReadOnly Property DataBuilderDefaultDir_3() As String
            Get
                Return ResourceManager.GetString("DataBuilderDefaultDir_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C:\Program Files\VistaDB 2.1\Tools\Data Builder\DataBuilder.exe.
        '''</summary>
        Friend ReadOnly Property DataBuilderDefaultPath() As String
            Get
                Return ResourceManager.GetString("DataBuilderDefaultPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C:\Program Files\VistaDB 3.0\Tools\Data Builder\Bin\DataBuilder.exe.
        '''</summary>
        Friend ReadOnly Property DataBuilderDefaultPath_3() As String
            Get
                Return ResourceManager.GetString("DataBuilderDefaultPath_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RootDir.
        '''</summary>
        Friend ReadOnly Property DataBuilderRegKey() As String
            Get
                Return ResourceManager.GetString("DataBuilderRegKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HKEY_CURRENT_USER\Software\Vista Software\VistaDB.
        '''</summary>
        Friend ReadOnly Property DataBuilderRegPath() As String
            Get
                Return ResourceManager.GetString("DataBuilderRegPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HKEY_CURRENT_USER\Software\Vista Software\VistaDB3.
        '''</summary>
        Friend ReadOnly Property DataBuilderRegPath_3() As String
            Get
                Return ResourceManager.GetString("DataBuilderRegPath_3", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property exit_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Grid_Footers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grid_Footers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Highlight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Highlight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property horizontal_solution_PP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("horizontal_solution_PP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property keys() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keys", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to d-MMM-yy.
        '''</summary>
        Friend ReadOnly Property MediumDate() As String
            Get
                Return ResourceManager.GetString("MediumDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.meikleprogramming.com/software/vdbcompare/manual/.
        '''</summary>
        Friend ReadOnly Property OnlineManual() As String
            Get
                Return ResourceManager.GetString("OnlineManual", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property play_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://code.google.com/p/vdbcompare/.
        '''</summary>
        Friend ReadOnly Property ProjectUrl() As String
            Get
                Return ResourceManager.GetString("ProjectUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://code.google.com/p/vdbcompare/issues/list.
        '''</summary>
        Friend ReadOnly Property ProjectUrl_Issues() As String
            Get
                Return ResourceManager.GetString("ProjectUrl_Issues", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Schema_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Schema_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shareit_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shareit_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to yyyy-MM-dd.
        '''</summary>
        Friend ReadOnly Property SqlDateFormat() As String
            Get
                Return ResourceManager.GetString("SqlDateFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to yyyy-MM-dd HH:mm.
        '''</summary>
        Friend ReadOnly Property SqlDateTimeFormat() As String
            Get
                Return ResourceManager.GetString("SqlDateTimeFormat", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property vDBCompare_Large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vDBCompare_Large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vDBCompare_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vDBCompare_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property VistaDB120x60w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VistaDB120x60w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.20.26.0.
        '''</summary>
        Friend ReadOnly Property VistaDBProviderVersion() As String
            Get
                Return ResourceManager.GetString("VistaDBProviderVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://www.vistadb.net.
        '''</summary>
        Friend ReadOnly Property VistaDBWebiste() As String
            Get
                Return ResourceManager.GetString("VistaDBWebiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to www.meikleprogramming.com.
        '''</summary>
        Friend ReadOnly Property WebSite() As String
            Get
                Return ResourceManager.GetString("WebSite", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
